T379994
Wikidata-Cameroon/WDAudioLex-BE pull request #4
Opened 2024-11-20 14:27 UTC by Ennyufedo

2024-11-20 14:29 UTC, Ennyufedo commented
> _ No description provided. _

@Wandji69 Please help me review this

2024-11-26 15:50 UTC, eugeneegbe commented
@Ennyufedo Can you do well to correctly rename your PRs.

2024-12-02 18:24 UTC, Ennyufedo commented
Plea

> @Ennyufedo Can you do well to correctly rename your PRs.
Please @eugeneegbe  do u mean my branch name? cos i find it difficult to edit PRs. or have u rectified it cos i was also seeing that u changed the tittle

2024-12-02 18:41 UTC, Bonifaze commented
Yes he mean your branch repo. the task id on phabricator is T379993 check https://phabricator.wikimedia.org/T379993

2024-12-02 18:50 UTC, Ennyufedo commented
Done @eugeneegbe  Thank you @Bonifaze

2024-12-11 16:56 UTC, eugeneegbe commented
@Ennyufedo This looks great. Do you think this pull request covers [T381995](https://phabricator.wikimedia.org/T381995)?

2024-12-11 17:38 UTC, Bonifaze commented
> @Ennyufedo This looks great. Do you think this pull request covers [T381995](https://phabricator.wikimedia.org/T381995)?

Yes, the setup instruction is included for windows, but i am not conversant with mac Os so i am not sure if it covers mac os

2024-12-11 17:59 UTC, Bonifaze commented
> > @Ennyufedo This looks great. Do you think this pull request covers [T381995](https://phabricator.wikimedia.org/T381995)?
> 
> Yes, the setup instruction is included for windows, but i am not conversant with mac Os so i am not sure if it covers mac os

2025-01-13 23:04 UTC, eugeneegbe commented on README.md
> +2. Setup
These could be in bold as well as all other headings.

2025-01-13 23:05 UTC, eugeneegbe requested changes
Looks good! Just a few more changes and we are good to go!

2025-02-18 11:56 UTC, merged