Setups Cors for the microservice
Wikidata-Cameroon/WDAudioLex-BE pull request #8
Opened 2024-12-12 15:09 UTC by emmanuelmingo

Since I don't yet know the domain of the frontend, I made the CORS in so that all domains can access it for the main time and to check if it was working, I used postman to verify the api calls.

2025-01-13 19:47 UTC, eugeneegbe requested changes
The changes looks good. However, the folder structure introduced is not required

2025-01-13 20:00 UTC, emmanuelmingo commented
Okay, I will make sure to from the folder. But should I change the file name to CORS.py so that it can be easily identified, because that was the use of the folder

2025-01-17 16:29 UTC, emmanuelmingo reviewed
I have remove the file structure

2025-01-17 16:29 UTC, emmanuelmingo commented
I have removed the file structure

2026-04-02 09:25 UTC, eugeneegbe commented
@Wandji69 I am tagging you for this one.

2026-04-02 13:49 UTC, merged